# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "4000:4000"

  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: ziv
      POSTGRES_PASSWORD: ziv
      POSTGRES_DB: ziv
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:

  
